# fly.toml app configuration file generated for spoonfeed on 2024-06-24T01:58:13+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spoonfeed'
primary_region = 'sin'

[build]

[env]
  SPOONFEED_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
